# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
paginate:         5
paginate_path:    "/news/:num"

# Setup
title:            'BC Indigenous Funding Conference'
tagline:          'Connecting organizations with funders.'
description:      ''
url:              '//funding-conference.bcaafc.com'
baseurl:          '/'

author:
  name:           'Della Preston'
  url:            '//funding-conference.bcaafc.com'
